# Perintah untuk menghasilkan halaman login pengguna, kini dengan dukungan untuk email/password tradisional dan Google Single Sign-On.
description = "Generate the user login page component, now with support for both traditional email/password and Google Single Sign-On."

prompt = """
Generate a Vue 3 component file located at `src/views/LoginPage.vue`.

**1. Technical Requirements (CRUCIAL):**
- The component **MUST** use the `<script setup>` syntax with the Composition API.
- The entire UI **MUST** be built using Framework7-Vue components. This includes `<f7-page>`, `<f7-login-screen>`, `<f7-list>`, `<f7-list-input>`, and `<f7-button>`.
- All component state (like `username`, `password`, and `isLoading`) **MUST** be managed with reactive `ref()` variables.

**2. Component Logic:**
- Create `ref` variables for `username`, `password`, `isPasswordLoading`, and `isGoogleLoading`.
- Import and use the `ApiClient` singleton.
- Import and use the Pinia `authStore`.
- Import and use `vue-router`.
- Implement `handlePasswordLogin()`: a method for the traditional form submission. It should set `isPasswordLoading` to true, call the API, handle success (save token, navigate to '/home'), handle errors, and finally set `isPasswordLoading` to false.
- Implement `handleGoogleLogin()`: a method for the Google login button. This method will be responsible for initiating the client-side Google authentication flow. Upon receiving a token from Google, it will call a specific method on the `ApiClient` (e.g., `loginWithGoogle(token)`). It should manage the `isGoogleLoading` state.

**3. Template Structure:**
- Use an `<f7-page login-screen>` as the root element.
- Include a title like "Cerdas CAPI".
- **Traditional Login Form:**
  - Use an `<f7-list form>` for the username and password inputs.
  - Use an `<f7-list-button>` for the "Login" button.
    - This button should be disabled when `isPasswordLoading` or `isGoogleLoading` is true.
    - It should show a preloader when `isPasswordLoading` is true.
- **Separator:**
  - Include a clear visual separator (e.g., `<f7-block-title>Atau</f7-block-title>`) between the two login methods.
- **Google Login Button:**
  - Use an `<f7-button large fill social="google" @click="handleGoogleLogin">Login dengan Google</f7-button>`.
  - This button should be disabled when `isPasswordLoading` or `isGoogleLoading` is true.
  - It should show a preloader when `isGoogleLoading` is true.
- Display any login errors returned from the API in an `<f7-block>` or a toast notification.
"""
